wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 3
      - 8
      4: 3.8.5
      5: 0.10.22
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 30
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.005
neuroneLayer1:
  desc: null
  value: 30
neuroneLayer2:
  desc: null
  value: 30
