wandb_version: 1

NETW_UPDATE_FREQ:
  desc: null
  value: 100
UPDATE_FREQ:
  desc: null
  value: 8
_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      4: 3.8.5
      5: 0.10.22
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 32
n_episode:
  desc: null
  value: 1000
n_epsiode_test:
  desc: null
  value: 10
nbr_job_max:
  desc: null
  value: 1
nbr_machines:
  desc: null
  value: 14
nbr_operation_max:
  desc: null
  value: 14
nbr_operator:
  desc: null
  value: 12
params_agent:
  desc: null
  value:
    epsilon: 1
    epsilon_decay: 0.9992
    epsilon_min: 0.05
    gamma: 0.95
    learning_rate: 0.0001
    memory: 20000
    model:
      activation_first_layer: relu
      activation_second_layer: relu
      loss: huber_loss
      nbr_neurone_first_layer: 14
      nbr_neurone_second_layer: 28
      optimizer: Adam
      output_layer_activation: linear
